### ISSUE TITLE
Add contact no. and name of event organisers of all events in events.js in shared folder

### ISSUE THREAD

**Issue by cjchirag7** [cjchirag7/concetto_front#36]
Use the excel sheet sent privately to you and update the details. 
Modify the admin field of each event in that file.
Eg. For RoboISM - 
admins: ["Shambhav G - 7844949368", "Srajan G - 8223060677", "Shantanu Rawat - 9424697088", "Sourav Sahu - 8825268970"]

**Comment by cjchirag7** [comment]
@shubhamSrivas , look into this issue and fix this by tommorow.

**Comment by shubhamSrivas** [comment]
Issue resolved
