### ISSUE TITLE
Center the button for register in Mobile View of Event Detail Page of a particular event

### ISSUE THREAD

**Issue by cjchirag7** [cjchirag7/concetto_front#37]

**Comment by prajwalMR** [comment]
I would like to take a shot at this issue

**Comment by prajwalMR** [comment]
Can you elaborate on what you mean by centre button?

**Comment by cjchirag7** [comment]
![Button center](https://user-images.githubusercontent.com/45796806/66257173-40924200-e7b3-11e9-8a00-0b1999905b11.png)
See the **blue Register button**, you just need to center this button inside the div, which it lies.
